"""Generate paper/tables/*.tex from frozen evaluator artifacts.

Every number in the emitted tables comes from a frozen-evaluator JSON in
runs/ (mirrored on S3). Verdict WORDS that the evaluators printed to the
research log but did not serialize (M4b PASS, M4a/c INSTRUMENT-INVALID,
the pre-tag dn15 FALSIFIED) are transcribed here as documented constants
with their logged source; no numeric value is hand-entered anywhere.

  python scripts/make_paper_tables.py
"""

import json
from pathlib import Path

RUNS = Path("runs")
OUT = Path("paper/tables")

PHASE_FAMILIES = ["pronoun_gender_ref", "reflexive_gender", "det_an_choice",
                  "a_an_adjective", "irregular_past", "negation_bare_verb"]
# column labels are the unique-data/params (D/N) value of the cell,
# grouped under a corpus header in phase_table()
PHASE_CELLS = [("packed", "packed"), ("dn5", "5"), ("dn15", "1.5"),
               ("web", "packed"), ("webdn5", "5"), ("webdn15", "1.5")]
FAM_TEX = {
    "pronoun_gender_ref": r"pronoun\_gender (focal)",
    "reflexive_gender": r"reflexive\_gender",
    "det_an_choice": r"det\_an\_choice",
    "a_an_adjective": r"a\_an\_adjective",
    "irregular_past": r"irregular\_past",
    "negation_bare_verb": r"negation\_bare\_verb",
}


def j(name):
    return json.loads((RUNS / name).read_text())


def phase_letters(s):
    # uppercase = classifiable verdict; lowercase in the frozen table =
    # agree-control gate failed -> rendered as a grey letter, never
    # promoted to a valid-looking verdict
    out = []
    for ch in s:
        if ch.islower():
            out.append(r"\textcolor{gray}{%s}" % ch.upper())
        else:
            out.append(ch)
    return r"\texttt{%s}" % "".join(out)


def phase_table():
    t = j("phase_table_rvp31.json")["table"]
    rows = []
    for f in PHASE_FAMILIES:
        cells = " & ".join(phase_letters(t[f"{f}|{c}"]) for c, _ in PHASE_CELLS)
        rows.append(f"{FAM_TEX[f]} & {cells} \\\\")
    head = " & ".join(h for _, h in PHASE_CELLS)
    return "\n".join([
        r"% AUTO-GENERATED by scripts/make_paper_tables.py from",
        r"% runs/phase_table_rvp31.json -- do not edit by hand.",
        r"\begin{tabular}{@{}l cccccc@{}}",
        r"\toprule",
        r" & \multicolumn{3}{c}{TinyStories ($D/N$)}"
        r" & \multicolumn{3}{c}{web ($D/N$)} \\",
        r"\cmidrule(lr){2-4} \cmidrule(lr){5-7}",
        f"family & {head} \\\\",
        r"\midrule",
        *rows,
        r"\bottomrule",
        r"\end{tabular}",
    ])


def ratio_tex(v):
    if v >= 100:
        return f"{v:,.0f}".replace(",", r"{,}")
    return f"{v:.2f}"


def step6_table():
    cells = j("eval_step6.json")["cells"]
    # rule:prior window ratio per corpus. Kill rows: battery girl-name
    # cues (f*-v2 counter). Rescue rows: injected, battery-disjoint cue
    # names (rescue-cue counter, DECISIONS 2026-06-11), starred. Web
    # base: battery girl names are not single tokens in the web vocab,
    # so the frozen counter cannot measure the class (dash).
    ratio_src = {
        "v1_repro": ("support_ts_window.json", ""),
        "kill_p437": ("support_kill_p437_window.json", ""),
        "kill_p645": ("support_kill_p645_window.json", ""),
        "kill_p1000": ("support_kill_p1000_window.json", ""),
        "web_packed_v2": (None, ""),
        "rescue_d001": ("support_rescuecues_rescue_d001_window.json", "*"),
        "rescue_d010": ("support_rescuecues_rescue_d010_window.json", "*"),
        "rescue_d100": ("support_rescuecues_rescue_d100_window.json", "*"),
        "rescue_d300": ("support_rescuecues_rescue_d300_window.json", "*"),
    }
    order = [("v1_repro", "TS base", "---"),
             ("kill_p437", "kill", "0.437"),
             ("kill_p645", "kill", "0.645"),
             ("kill_p1000", "kill", "1.0"),
             ("web_packed_v2", "web base", "---"),
             ("rescue_d001", "rescue", "0.01"),
             ("rescue_d010", "rescue", "0.1"),
             ("rescue_d100", "rescue", "1.0"),
             ("rescue_d300", "rescue", "3.0")]
    valid = j("eval_step6.json")["verdicts"]["kill_cell_intervention_valid"]
    rows = []
    id_map = []
    for cell, arm, dose in order:
        st = cells[cell]["stats"]
        note = ""
        if cell in valid and not valid[cell]:
            note = r"\textsuperscript{\dag}"
        src, star = ratio_src[cell]
        if src is None:
            ratio = "---"
        else:
            r_ = j(src)["classes"]["girl_names"]["support_ratio"]
            ratio = f"{ratio_tex(r_)}{star}"
        id_map.append(f"%   {arm} {dose} = {cell}")
        rows.append(
            f"{arm} & {dose}{note} & {ratio} & "
            f"{st['recovered_valid']}/{st['n']} & {st['died']}/{st['n']} & "
            f"{st['cm_n_valid']} & ${st['cm_final_mean']:+.2f}$ " + r"\\")
    return "\n".join([
        r"% AUTO-GENERATED by scripts/make_paper_tables.py from",
        r"% runs/eval_step6.json and runs/support_*_window.json",
        r"% -- do not edit by hand. Row -> run-cell ID:",
        *id_map,
        r"\begin{tabular}{@{}l r r ccc r@{}}",
        r"\toprule",
        r"arm & dose & rule:prior & rec/3 & died/3 & "
        r"$\cm$-valid & mean $\cm$ \\",
        r"\midrule",
        *rows,
        r"\bottomrule",
        r"\end{tabular}",
    ])


# Verdict classes for the prediction ledger. Every row is one of:
#   PASS / FAIL          scored against its frozen threshold
#   UNSC                 unscoreable under a registered validity gate
#                        (never converted to PASS or FAIL)
PASS, FAIL, UNSC = "pass", "fail", "unsc"
MARK = {PASS: r"\predpass", FAIL: r"\predfail", UNSC: r"\predunsc"}


def prediction_rows():
    """One row per registered prediction: (label, class, note).

    Grouped; each group carries its falsifier status. Classes come
    from the frozen artifacts; the two non-serialized verdict WORDS
    (the pre-grid dn15 falsification, M4b) are documented constants
    with their logged source, as before.
    """
    pred = j("eval_predictions_rvp1.json")["report"]
    pub = j("eval_public_suite_rvp31.json")["report"]
    fst = j("eval_fstar_rvp31.json")
    m3 = j("eval_m3_rvp31.json")
    m4p = j("eval_m4prime.json")
    s6 = j("eval_step6.json")["verdicts"]
    s6t = j("eval_step6t.json")["verdicts"]
    r5 = j("eval_rvp5_full.json")["verdicts"]
    ak = j("eval_ankill.json")["report"]

    def b(v):
        return PASS if v is True else FAIL if v is False else UNSC

    def v6(k):
        return b(s6[k]) if isinstance(s6[k], bool) else UNSC

    def v6t(k):
        return b(s6t[k]) if isinstance(s6t[k], bool) else UNSC

    # group name, falsifier status (None = none registered,
    # False = silent, True = triggered), rows
    groups = [
        ("Budget-only pilot (pre-grid)", None, [
            # logged 2026-06-10; gate extended pre-web (timeline row 2)
            (r"$\dn{=}1.5$ displacement predictions", FAIL, "falsified"),
        ]),
        ("Phase grid (Step 3)", bool(pred["KILL"]), [
            ("P1 focal rule: survives all TS, dies web-packed",
             b(pred["P1"]), ""),
            ("P2 high-support families survive web", b(pred["P2"]), ""),
            ("P3 reflexive below 0.8 on web", b(pred["P3"]), ""),
            (r"P4 web budget ordering (packed $\leq$ d15)",
             b(pred["P4"]), ""),
        ]),
        ("Public suite (Pythia/OLMo)", None, [
            ("PUB1 boundary-case census", b(pub["PUB1"]), "decomposed"),
            ("PUB2 pythia-70m displacement depth", b(pub["PUB2"]),
             "by 0.008"),
            ("PUB2$'$ secondary (reflexive)", b(pub["PUB2_secondary"]), ""),
            (r"PUB3 depth vs.\ scale ordering", b(pub["PUB3"]), ""),
        ]),
        # fst["FALSIFIER"] is True when the hard-falsifier check came
        # back clean (locked reading: "hard falsifier NOT triggered")
        ("Critical-frequency theory (Step 4)", not fst["FALSIFIER"], [
            ("F1 support-ratio/outcome ordering",
             b(fst["F1_spearman_all_web_cells"]), ""),
            ("F2 displaced families lowest ratio",
             b(fst["F2_displaced_lowest"]), ""),
        ]),
        ("Mechanism (Step 5)", bool(m4p["FALSIFIER_triggered"]), [
            ("M1/M2 $S_1$ embedding-geometry scalar", UNSC,
             "instrument failure"),  # post-mortem logged, never patched
            ("M3 no memorized-template residue", b(m3["M3"]), ""),
            (r"M4b $\cm$ zero-cross times collapse", PASS,
             ""),  # logged read; rows in runs/eval_m4.json
            ("M4a/M4c displacement direction", UNSC,
             "$<2$ valid seeds"),  # web s44 0.5-nat guard
            ("M4$'$-TS sign prediction, TS cells", b(m4p["M4pTS"]), ""),
            ("M4$'$-A sign prediction, all cells", b(m4p["M4pA"]),
             "falsifier hit"),
        ]),
        ("Causal control (Step 6): rescue",
         bool(s6["R_FALSIFIER_triggered"]), [
            (r"R1 behavioral rescue at $d{\geq}1$", v6("R1_beh"), ""),
            (r"R1 $\cm$ crosses positive at $d{=}1$", v6("R1_cm"), ""),
            (r"R1c behavioral rescue at $d{=}3$", v6("R1c_beh"), ""),
            (r"R1c $\cm$ at $d{=}3$", v6("R1c_cm"), "0 $\\cm$-valid seeds"),
            ("R2 no rescue at trace dose", v6("R2_beh"), ""),
            (r"R2 trace-dose $\cm$", v6("R2_cm"), "0 $\\cm$-valid seeds"),
            (r"R3 dose monotonicity $\rho\geq0.8$", v6("R3_graded"),
             f"$\\rho={s6['rho_rescue']:+.2f}$"),
            ("RS rescue specificity", v6("RS_specificity"), ""),
        ]),
        ("Causal control (Step 6): kill",
         bool(s6["K_FALSIFIER_triggered"]), [
            (r"K1 super-critical kill ($p{=}.645$), beh.", v6("K1_beh"),
             "KS gate"),
            (r"K1 super-critical kill ($p{=}.645$), $\cm$", v6("K1_cm"),
             "KS gate"),
            (r"K1c full kill ($p{=}1$), behavioral", v6("K1c_beh"), ""),
            (r"K1c full kill ($p{=}1$), $\cm$", v6("K1c_cm"), ""),
            (r"K2 dose monotonicity $\rho\leq-0.8$", v6("K2_graded"),
             f"$\\rho={s6['rho_kill']:+.2f}$"),
        ]),
        ("Rescue timing (Step-6T)",
         bool(s6t["T_FALSIFIER_triggered"]), [
            ("T1 early-window dose rescues, beh.", v6t("T1_beh"), ""),
            (r"T1 early-window $\cm$ ends positive", v6t("T1_cm"),
             "G4 gate (1/3 valid)"),
            ("T2 late-window dose fails, beh.", v6t("T2_beh"), ""),
            (r"T3 early ${>}$ late $\cm$ ordering", v6t("T3_ord"),
             "G4 gate"),
        ]),
        ("Second-rule (a/an) kill ladder", None, [
            ("AK1 dose monotonicity (cell means)", b(ak["AK1"]), ""),
            (r"AK2 full flip ($p{=}1$) kills", b(ak["AK2"]), ""),
            (r"AK3 boundary within $2\times$ of pronoun's",
             b(ak["AK3"]), "crossed lower"),
            ("AK4 agree-gate failure at high dose", b(ak["AK4"]),
             "gate stayed valid"),
            ("AK5 dissociation (unrelated families)", b(ak["AK5"]), ""),
        ]),
        ("OOD transfer (rvp5)", bool(r5["RV5_F_triggered"]), [
            ("RV5-P1 competence transfers", b(r5["RV5_P1"]), ""),
            ("RV5-P2 failure transfers", b(r5["RV5_P2"]), ""),
            ("RV5-P3 transience transfers", b(r5["RV5_P3"]), ""),
        ]),
    ]
    return groups, s6["hit_rate"]


def falsifier_word(status):
    if status is None:
        return "---"
    return r"\textbf{triggered}" if status else "silent"


def predictions_summary():
    groups, hr = prediction_rows()
    lines = [
        r"% AUTO-GENERATED by scripts/make_paper_tables.py from frozen",
        r"% evaluator artifacts in runs/ -- do not edit by hand.",
        r"\begin{tabular}{@{}l ccc l@{}}",
        r"\toprule",
        r"prediction group & \predpass & \predfail & \predunsc"
        r" & falsifier \\",
        r"\midrule",
    ]
    tot = {PASS: 0, FAIL: 0, UNSC: 0}
    for gname, fals, rows in groups:
        n = {PASS: 0, FAIL: 0, UNSC: 0}
        for _, cls, _ in rows:
            n[cls] += 1
            tot[cls] += 1
        lines.append(f"{gname} & {n[PASS]} & {n[FAIL]} & {n[UNSC]} & "
                     f"{falsifier_word(fals)} \\\\")
    n_trig = sum(1 for _, fals, _ in groups if fals is True)
    n_reg = sum(1 for _, fals, _ in groups if fals is not None)
    lines += [
        r"\midrule",
        f"all & {tot[PASS]} & {tot[FAIL]} & {tot[UNSC]} & "
        f"{n_trig} of {n_reg} \\\\",
        r"\bottomrule",
        r"\end{tabular}",
    ]
    return "\n".join(lines)


def predictions_ledger():
    groups, hr = prediction_rows()
    lines = [
        r"% AUTO-GENERATED by scripts/make_paper_tables.py from frozen",
        r"% evaluator artifacts in runs/ -- do not edit by hand.",
        r"\begin{tabular}{@{}l c l@{}}",
        r"\toprule",
        r"registered prediction & verdict & note \\",
        r"\midrule",
    ]
    for gname, fals, rows in groups:
        fnote = "" if fals is None else \
            f" (falsifier {'triggered' if fals else 'silent'})"
        lines.append(r"\multicolumn{3}{@{}l}{\emph{%s%s}} \\"
                     % (gname, fnote))
        for label, cls, note in rows:
            lines.append(f"\\quad {label} & {MARK[cls]} & {note} \\\\")
    lines += [
        r"\midrule",
        r"Blind directional hit rate (Step 6) & "
        f"\\multicolumn{{2}}{{l}}{{{hr['hits']}/{hr['scored']} scored "
        f"({hr['registered']} registered, "
        f"{len(hr['unscoreable'])} unscoreable)}} \\\\",
        r"\bottomrule",
        r"\end{tabular}",
    ]
    return "\n".join(lines)


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    for name, content in [("phase_rvp31.tex", phase_table()),
                          ("step6_doses.tex", step6_table()),
                          ("predictions_summary.tex", predictions_summary()),
                          ("predictions.tex", predictions_ledger())]:
        (OUT / name).write_text(content + "\n")
        print(f"wrote paper/tables/{name}")


if __name__ == "__main__":
    main()
