"""Generate the a/an-kill ladder LaTeX table (registered blind
predictions AK1-AK5, DECISIONS.md 2026-06-11).

Reads runs/ankill_p*_s4?/probe_log_rvp31.jsonl, runs/v1_repro_s4?/
probe_log_rvp31.jsonl and runs/ankill_manifests/p*.json; applies the
frozen gate_a_classify conventions (letters, finals); emits
paper/tables/ankill_tbl.tex. No hand-entered numbers.

  python scripts/table_ankill.py [--out paper/tables]
"""

import argparse
import json
from pathlib import Path

import sys
sys.path.insert(0, "scripts")
from gate_a_classify import classify, load_traj

SEEDS = (42, 43, 44)
DOSES = [(0.5, 500), (0.667, 667), (0.75, 750), (0.9, 900), (1.0, 1000)]
LETTER = {"RECOVERED": "R", "DISPLACED": "D", "PARTIAL": "P",
          "NEVER": "N", "UNSTABLE": "U"}
HDR = "% generated by scripts/table_ankill.py -- do not edit"


def cells():
    rows = [("0 (base)", "v1_repro", None)]
    for p, tag in DOSES:
        rows.append((f"{p:g}", f"ankill_p{tag}", tag))
    return rows


def ratio(tag):
    if tag is None:
        k = json.load(open("runs/ankill_manifests/p500.json"))["an_kill"]
        return k["eligible"] / k["a_vowel_base"]
    k = json.load(open(f"runs/ankill_manifests/p{tag}.json"))["an_kill"]
    return k["post_kill_ratio"]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="paper/tables")
    args = ap.parse_args()

    lines = [HDR, "\\begin{tabular}{lrlllrr}", "\\toprule",
             " & & \\multicolumn{4}{c}{\\texttt{det\\_an\\_choice}} & "
             "\\texttt{a\\_an\\_adj.} \\\\",
             "\\cmidrule(lr){3-6}",
             "flip rate $p$ & rule:counter & "
             "\\multicolumn{3}{c}{final (letter), seeds 42/43/44} & mean "
             "& mean \\\\", "\\midrule"]
    for disp, cell, tag in cells():
        res = [classify(load_traj(f"runs/{cell}_s{s}", "rvp31"))
               for s in SEEDS]
        da = [r["det_an_choice"] for r in res]
        aa = [r["a_an_adjective"] for r in res]
        seedcols = " & ".join(
            f"${r['conflict_final']:.2f}$\\,({LETTER[r['class']]})" for r in da)
        r = ratio(tag)
        rs = f"{r:.2f}" if r < 10 else f"{r:.1f}"
        lines.append(
            f"{disp} & {rs} & {seedcols} & "
            f"${sum(x['conflict_final'] for x in da)/3:.2f}$ & "
            f"${sum(x['conflict_final'] for x in aa)/3:.2f}$ \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    out = Path(args.out) / "ankill_tbl.tex"
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
