"""Generate LaTeX appendix tables for the n-gram baseline (threat T13).

Reads the ngram_baseline JSONs (mirrored from
s3://fogen-phase/runs/ngram_baseline/) and emits:
  - ngram_pronoun.tex: pronoun family, heldout, orders 2 and 5, all cells;
  - ngram_full.tex: all 12 families x all cells, order 5, heldout,
    grouped into one table per corpus group.

  python scripts/table_ngram_baseline.py \
      --dir runs/ngram_baseline --out paper/tables
"""

import argparse
import json
from pathlib import Path

GROUPS = [
    ("TinyStories base and kill cells",
     ["v1_repro", "kill_p437", "kill_p645", "kill_p1000"]),
    ("Web base and rescue cells",
     ["web_packed_v2", "rescue_d001", "rescue_d010", "rescue_d100",
      "rescue_d300"]),
    ("Data-budget cells",
     ["databudget_dn5", "databudget_dn15", "web_dn5", "web_dn15"]),
]
CELL_ORDER = [c for _, cells in GROUPS for c in cells]
DISPLAY = {
    "v1_repro": "TS base", "kill_p437": "kill p437",
    "kill_p645": "kill p645", "kill_p1000": "kill p1000",
    # cell names encode dose x 100 (d100 = 1.0 x delta_TS)
    "web_packed_v2": "web base", "rescue_d001": "rescue d=0.01",
    "rescue_d010": "rescue d=0.1", "rescue_d100": "rescue d=1",
    "rescue_d300": "rescue d=3", "databudget_dn5": "TS D/N=5",
    "databudget_dn15": "TS D/N=15", "web_dn5": "web D/N=5",
    "web_dn15": "web D/N=15",
}


def load(dir_):
    cells = {}
    for f in sorted(Path(dir_).glob("ngram_*.json")):
        d = json.load(open(f))
        cells[d["cell"]] = d
    missing = [c for c in CELL_ORDER if c not in cells]
    assert not missing, f"missing cells: {missing}"
    return cells


def acc(cell_data, order, probe, split="heldout"):
    for r in cell_data["orders"][str(order)]:
        if r["probe"] == probe and r["split"] == split:
            return r["argmax_acc"]
    raise KeyError((order, probe, split))


def pronoun_table(cells):
    lines = [
        "% generated by scripts/table_ngram_baseline.py -- do not edit",
        "\\begin{table}[t]",
        "\\caption{Stupid-backoff $n$-gram baseline "
        "($\\alpha=0.4$) on the frozen battery, pronoun family, heldout "
        "split, forced-choice argmax accuracy. The baseline is counted on "
        "the exact token stream each cell's model saw.}",
        "\\label{tab:ngram-pronoun}",
        "\\vskip 0.1in",
        "\\centering\\small",
        "\\begin{tabular}{lcccc}",
        "\\toprule",
        " & \\multicolumn{2}{c}{$n=2$} & \\multicolumn{2}{c}{$n=5$} \\\\",
        "\\cmidrule(lr){2-3}\\cmidrule(lr){4-5}",
        "Cell & conflict & agree & conflict & agree \\\\",
        "\\midrule",
    ]
    prev_group_end = {cells_[-1] for _, cells_ in GROUPS[:-1]}
    for c in CELL_ORDER:
        d = cells[c]
        vals = [acc(d, o, f"pronoun_gender_ref.{cond}")
                for o in (2, 5) for cond in ("conflict", "agree")]
        lines.append(f"{DISPLAY[c]} & " +
                     " & ".join(f"{v:.2f}" for v in vals) + " \\\\")
        if c in prev_group_end:
            lines.append("\\midrule")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]
    return "\n".join(lines)


def full_tables(cells):
    fams = sorted({r["probe"].split(".")[0]
                   for r in cells["v1_repro"]["orders"]["5"]})
    out = ["% generated by scripts/table_ngram_baseline.py -- do not edit"]
    for gi, (gname, gcells) in enumerate(GROUPS):
        ncol = len(gcells)
        out += [
            "\\begin{table*}[t]",
            f"\\caption{{$5$-gram baseline, all families, heldout argmax "
            f"accuracy (conflict / agree): {gname}.}}",
            f"\\label{{tab:ngram-full-{gi}}}",
            "\\vskip 0.1in",
            "\\centering\\small",
            "\\begin{tabular}{l" + "c" * ncol + "}",
            "\\toprule",
            "Family & " + " & ".join(DISPLAY[c] for c in gcells) + " \\\\",
            "\\midrule",
        ]
        for fam in fams:
            row = [fam.replace("_", "\\_")]
            for c in gcells:
                cf = acc(cells[c], 5, f"{fam}.conflict")
                ag = acc(cells[c], 5, f"{fam}.agree")
                row.append(f"{cf:.2f} / {ag:.2f}")
            out.append(" & ".join(row) + " \\\\")
        out += ["\\bottomrule", "\\end{tabular}", "\\end{table*}", ""]
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dir", default="runs/ngram_baseline")
    ap.add_argument("--out", default="paper/tables")
    args = ap.parse_args()

    cells = load(args.dir)
    outdir = Path(args.out)
    outdir.mkdir(parents=True, exist_ok=True)
    (outdir / "ngram_pronoun.tex").write_text(pronoun_table(cells))
    (outdir / "ngram_full.tex").write_text(full_tables(cells))
    print(f"wrote {outdir}/ngram_pronoun.tex and ngram_full.tex "
          f"({len(cells)} cells)")


if __name__ == "__main__":
    main()
