"""Generate LaTeX tables for the borrowed mechanism analyses
(DECISIONS.md 2026-06-11, post-hoc/descriptive).

Reads runs/<run>/mech_heads.jsonl, runs/<run>/mech_patch.json and
runs/bootstrap_cis_g*.json and emits to paper/tables/:
  - mech_heads_tbl.tex: dominant last-position head at the CM peak and
    at the final checkpoint: attribution share, zero-ablation effect,
    OV-cosine with the she-he readout direction;
  - mech_patch_tbl.tex: top single component by recovery fraction when
    patched between the run's own peak and final checkpoints;
  - mech_cis.tex: stratified-bootstrap CIs on peak/final heldout
    conflict accuracy and their paired drop, gender families.

  python scripts/table_mech_borrowed.py [--out paper/tables]
"""

import argparse
import glob
import json
from pathlib import Path

import numpy as np

GROUPS = [
    ("TS base", "v1_repro"),
    ("web base", "web_packed_v2"),
    ("kill $p{=}1$", "kill_p1000"),
    ("rescue $d{=}1$", "rescue_d100"),
    ("rescue $d{=}3$", "rescue_d300"),
]
SEEDS = (42, 43, 44)
FAMS = [("pronoun\\_gender\\_ref", "pronoun_gender_ref"),
        ("reflexive\\_gender", "reflexive_gender")]
HDR = "% generated by scripts/table_mech_borrowed.py -- do not edit"


def load_run(run):
    rows = sorted((json.loads(l) for l in open(f"runs/{run}/mech_heads.jsonl")),
                  key=lambda r: r["step"])
    pat = json.loads(Path(f"runs/{run}/mech_patch.json").read_text())
    return rows, pat


def head_stats(rows, step):
    r = next(x for x in rows if x["step"] == step)
    c = np.array(r["C_heads"])
    l, h = np.unravel_index(np.abs(c).argmax(), c.shape)
    share = abs(c[l, h]) / np.abs(c).sum()
    return (f"L{l}H{h}", share, r["abl_CM"][l][h] - r["CM"],
            r["ov_cos"][l][h], r["CM"])


def heads_table():
    lines = [HDR, "\\begin{table}[htbp]", "\\caption{"
             "Dominant last-position head per run (largest $|$attribution$|$ "
             "to the pre-softcap \\emph{she}--\\emph{he} gap), at the run's "
             "own $\\cm$-peak checkpoint and at the final checkpoint. "
             "share = that head's fraction of total head-level "
             "$|$attribution$|$; $\\Delta\\cm_{\\mathrm{abl}}$ = change in "
             "post-softcap $\\cm$ when the head's output is zeroed at all "
             "positions; cos = cosine of the head's mean OV output on "
             "feminine cue tokens with $w_{she}-w_{he}$. Descriptive, "
             "post-hoc (App.~\\ref{app:mech2}).}",
             "\\label{tab:mech-heads}", "\\vskip 0.1in",
             "\\centering\\small",
             "\\begin{tabular}{llrlrrrrlrrr}", "\\toprule",
             " & & \\multicolumn{5}{c}{at $\\cm$ peak} & "
             "\\multicolumn{5}{c}{at final} \\\\",
             "\\cmidrule(lr){3-7}\\cmidrule(lr){8-12}",
             "Cell & seed & $\\cm$ & head & share & "
             "$\\Delta\\cm_{\\mathrm{abl}}$ & cos & $\\cm$ & head & share & "
             "$\\Delta\\cm_{\\mathrm{abl}}$ & cos \\\\", "\\midrule"]
    for gi, (disp, cell) in enumerate(GROUPS):
        if gi:
            lines.append("\\midrule")
        for s in SEEDS:
            rows, pat = load_run(f"{cell}_s{s}")
            p = head_stats(rows, pat["peak_step"])
            f = head_stats(rows, pat["final_step"])
            lines.append(
                f"{disp if s == 42 else ''} & {s} & "
                f"${p[4]:+.2f}$ & {p[0]} & {p[1]:.2f} & ${p[2]:+.2f}$ & "
                f"${p[3]:+.2f}$ & "
                f"${f[4]:+.2f}$ & {f[0]} & {f[1]:.2f} & ${f[2]:+.2f}$ & "
                f"${f[3]:+.2f}$ \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    return "\n".join(lines)


def patch_table():
    def top(res):
        k = max(res, key=lambda k: res[k]["recovery"] or -9e9)
        name = k.replace("head:", "head L").replace("mlp:", "MLP ")
        if name.startswith("head L"):
            l, h = name[6:].split(":")
            name = f"head L{l}H{h}"
        return name, res[k]["recovery"]

    lines = [HDR, "\\begin{table}[htbp]", "\\caption{"
             "Single-component activation patching between each run's own "
             "$\\cm$-peak and final checkpoints (cached component outputs "
             "on the frozen feminine-cue prompts, swapped at all "
             "positions). Each entry is the component with the largest "
             "recovery fraction "
             "$(\\cm_{\\mathrm{patch}}-\\cm_{\\mathrm{dst}})/"
             "(\\cm_{\\mathrm{src}}-\\cm_{\\mathrm{dst}})$; fractions "
             "above $1$ overshoot the source value. Descriptive, post-hoc "
             "(App.~\\ref{app:mech2}).}",
             "\\label{tab:mech-patch}", "\\vskip 0.1in",
             "\\centering\\small",
             "\\begin{tabular}{lllrlr}", "\\toprule",
             " & & \\multicolumn{2}{c}{peak $\\to$ final} & "
             "\\multicolumn{2}{c}{final $\\to$ peak} \\\\",
             "\\cmidrule(lr){3-4}\\cmidrule(lr){5-6}",
             "Cell & seed & component & rec. & component & rec. \\\\",
             "\\midrule"]
    for gi, (disp, cell) in enumerate(GROUPS):
        if gi:
            lines.append("\\midrule")
        for s in SEEDS:
            _, pat = load_run(f"{cell}_s{s}")
            (nf, rf) = top(pat["patch"]["peak_into_final"])
            (nb, rb) = top(pat["patch"]["final_into_peak"])
            lines.append(f"{disp if s == 42 else ''} & {s} & "
                         f"{nf} & ${rf:+.2f}$ & {nb} & ${rb:+.2f}$ \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    return "\n".join(lines)


def cis_table():
    merged = {}
    for f in sorted(glob.glob("runs/bootstrap_cis_g*.json")):
        for k, v in json.loads(Path(f).read_text()).items():
            if k != "cells":
                merged[k] = v

    def fmt(r):
        return (f"${r['final_acc']:.2f}$ & ${r['drop']:+.2f}$ "
                f"\\,{{\\scriptsize$[{r['drop_ci95'][0]:+.2f},"
                f"{r['drop_ci95'][1]:+.2f}]$}}")

    lines = [HDR, "\\begin{table}[htbp]", "\\caption{"
             "Item-level bootstrap on the displaced gender families "
             "(heldout conflict split; pronoun $n{=}12$ items, reflexive "
             "$n{=}24$): final-checkpoint accuracy, and the peak-minus-"
             "final drop with its 95\\% CI from 10{,}000 "
             "template-stratified resamples applied jointly to the "
             "peak and final checkpoints (the pairing is preserved, so "
             "the drop CI accounts for item-level correlation). The peak "
             "checkpoint per family is the probe-log argmax snapped to "
             "the nearest stored checkpoint. The rescue $d{=}1$ seed-44 "
             "run is the registered blanket-\\emph{she} artifact-flagged "
             "run (App.~\\ref{app:rescue}); its near-zero pronoun drop "
             "fails the agree-condition control. Descriptive, post-hoc.}",
             "\\label{tab:mech-cis}", "\\vskip 0.1in",
             "\\centering\\small",
             "\\begin{tabular}{llrlrl}", "\\toprule",
             " & & \\multicolumn{2}{c}{pronoun\\_gender\\_ref} & "
             "\\multicolumn{2}{c}{reflexive\\_gender} \\\\",
             "\\cmidrule(lr){3-4}\\cmidrule(lr){5-6}",
             "Cell & seed & final & drop [95\\% CI] & final & "
             "drop [95\\% CI] \\\\", "\\midrule"]
    for gi, (disp, cell) in enumerate(GROUPS):
        if gi:
            lines.append("\\midrule")
        for s in SEEDS:
            r = merged[f"{cell}_s{s}"]["families"]
            cols = " & ".join(fmt(r[f]) for _, f in FAMS)
            lines.append(f"{disp if s == 42 else ''} & {s} & {cols} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="paper/tables")
    args = ap.parse_args()
    out = Path(args.out)
    for name, content in (("mech_heads_tbl.tex", heads_table()),
                          ("mech_patch_tbl.tex", patch_table()),
                          ("mech_cis.tex", cis_table())):
        (out / name).write_text(content + "\n")
        print(f"wrote {out / name}")


if __name__ == "__main__":
    main()
